### ISSUE TITLE
Syntax is out of date, various keywords and builtins missing

### ISSUE THREAD

**Issue by haltman-at** [highlightjs/highlightjs-solidity#2]
This package is fairly out of date; for instance, there's no recognition of `constructor` or `calldata` keywords.  There are various other things missing as well (e.g. the `abi` builtin; I won't bother listing them all), but those are the most obvious.  Thank you!

Edit: At @gnidan's suggestion I'm going to make a checklist for everything I found below.  I'm excluding stuff about assembly or 0.6.0 because it's not so clear it makes sense to do those.

- [ ] Remove singular time literals
- [ ] Add fixed-point types
- [ ] Add `payable`
- [ ] Add `calldata`
- [ ] Add `emit`
- [ ] Add pragma statements
- [ ] Add placeholder statement
- [ ] Add `constructor`
- [ ] Maybe add `for` in `using ... for ...` but that's probably unnecessary?
- [ ] Move `assert`, `revert`, `require` to their appropriate section
- [ ] Add `abi`, `blockhash` (as standalone),` gasleft`, `keccak256`, `type`, `suicide`
- [ ] Add `abi.decode`, `abi.encode`, `abi.encodePacked`, `abi.encodeWithSelector`, `abi.encodeWithSignature`
- [ ] Maybe add `msg.gas` and `msg.value` but that's probably unnecessary?
- [ ] Add `staticcall`, `transfer`, `pop`, `name`, `creationCode`, `runtimeCode`.
- [ ] Account for hex strings
- [ ] Maybe account for reserved-but-not-used words?

Things I would prefer but you might disagree with:

- [ ] De-highlight `self`
- [ ] Move `send`, `call`, `callcode`, `delegatecall` to their appropriate section

**Comment by marcoscaceres** [comment]
PR welcome 🙏 or, if you can list the things that are missing, that be a huge help.

**Comment by haltman-at** [comment]
OK, will try to compile a complete list later, possibly turn it into a PR assuming I can figure out the structure.  Thanks!

**Comment by haltman-at** [comment]
OK, here's a complete list of what I noticed is missing or incorrect.  Note that while my original issue was that this is out of date, that it didn't include post-0.5.0 syntax, I'm going to include pre-0.5.0 syntax that I notice is missing as well, because I'm assuming you want this to handle both.  I'm less familiar with pre-0.5.0, so I can't guarantee getting everything there, but I think this should be pretty comprehensive.

Note: I'm also going to include errors that you already know about or which are deliberate, because, hey, may as well make a complete record.

So, with that, let's start.

Is not syntax but is highlighted: `self`

You know about this one of course, having included it deliberately, but I still feel obligated to point it out.  (Could we perhaps get some sort of strict mode where `self` is not highlighted, and the other deliberate errors are also handled in a more strictly correct way rather than how you handled it?)

Literals that don't actually exist:

You've included the following literals that don't exist: `second`, `minute`, `hour`, day`, `week`, `year`.  Only the plurals actually work.

Missing types:

`fixed`, `ufixed`, and `fixedMxN` and `ufixedMxN` for appropriate values of M and N -- OK, you know about this one already.  This probably wouldn't be so bad to include if you autogenerated it.  Or you could start with just `fixed` and `ufixed`.

Missing type qualifiers or whatever they're called:

`payable`; the new location `calldata`

Missing statements:

`emit`, `pragma` (which obviously has both its `pragma solidity` and `pragma experimental` variants)

Other missing keywords:

`constructor`, also `for` (in the context of a `using` declaration... you seem to have `as` in `import`, but not `for` in `using`)

Builtins misclassified as keywords:

`assert`, `revert`, `require`

Builtin members misclassified as keywords:

`send`, `call`, `callcode`, `delegatecall` -- again, I know these were deliberate, but I still feel like I should point it out.  I'm going to put their missing analogues under "missing builtin members" rather than "missing members", if you don't mind.

Missing builtins:

`abi`, `blockhash` (you have `block.blockhash`, but `blockhash` is now a builtin by itself), `gasleft`, `keccak256`, `type`, `suicide`

Missing builtin members of specific magic variables:

`abi.decode`, `abi.encode`, `abi.encodePacked`, `abi.encodeWithSelector`, `abi.encodeWithSignature`.  I'm not sure whether `msg.gas` belongs here, because you do have `gas` as a generic member, so I'm guessing that also covers `msg.gas`?

Missing builtin members not of specific magic variables:

`staticcall` (for addresses, though I guess for consistency you'd probably put this under keyword instead), `transfer` (same note), `pop` (for storage arrays), `name` (for `type(C)` magic variables), `creationCode` (same), `runtimeCode` (same).

Other syntactic constructs I'm not sure are covered:

Hex strings of the form `hex"deadbeef..."` or `hex'deadbeef'....`

Finally, words that are reserved but currently unused:

`abstract`, `after`, `alias`, `apply`, `auto`, `case`, `catch`, `copyof`, `default`, `define`, `final`, `immutable`, `implements`, `in`, `inline`, `let`, `macro`, `match`, `mutable`, `null`, `of`, `override`, `partial`, `promise`, `reference`, `relocatable`, `sealed`, `sizeof`, `static`, `supports`, `switch`, `try`, `typedef`, `typeof`, `unchecked`

Of these, IIRC, `abstract` and I think also `override` are going to be introduced for real in 0.6.0.

That's all I could find.  Hope that's helpful.  Thanks again for putting this together!  Like I said, may turn this into a PR if I have time.

**Comment by haltman-at** [comment]
Sorry, a few additional notes I missed the first time around:

You may want to highlight the placeholder statement `_;`.  Not sure.

I don't know whether you want to highlight things that are assembly-only.  I'm guessing not, as that sounds like a fair bit more work for not a lot of gain.  Still, it is worth noting that `switch`, `case`, and `default` are available as keywords in Solidity assembly (even though they're not in proper Solidity).  Actually those three might be worth including, IDK (although I suppose they risk confusing people into believing that these things exist in proper Solidity, so maybe not!).  Then there's all the assembly opcodes, which no way am I going to list, but which can be found [here](https://solidity.readthedocs.io/en/v0.5.8/assembly.html#opcodes).  Again, probably not worth including, but thought I'd point it out.

Thanks again!

**Comment by haltman-at** [comment]
OK, sorry, one more thing.  I decided to go and take a look about what new syntax might be coming in 0.6.0.  Here's what I found, although note that since 0.6.0 isn't out yet this is necessarily tentative and you may want to ignore it for the time being:

New keywords `copy`, `virtual`, `override`, `abstract`, possibly `fallback`

...and I think that's it.

**Comment by pospi** [comment]
@haltman-at this is a really amazing contribution and must have taken you a lot of time to think through! As the original author I just wanted to chime in and say that I really appreciate it (:

Most of this is new stuff since I threw this together, non-plural keywords you might want to check (on the off-chance that they didn't exist in some old compiler version, but were taken out). The only one I really have a comment on is `self`- I see that as a *strong* convention (as it is in eg. Python, Rust); but I also see that you're coming from a purists perspective toward the semantics of the language and I appreciate that much more (I was coming at it mostly from aesthetics).

Unfortunately I have too many other things going on to be contributing to old code and I have no reason to write Solidity anymore, but I'll tweet this thread and see if some kind soul from the Ethereum community wants to help.

**Comment by haltman-at** [comment]
Glad to hear it! :)

Yeah I can't claim to have checked *every* version regarding singular time units, but I checked a bunch of versions of the docs and even tried it with a bunch of old compilers, and I can't find anything to indicate that those were ever part of the language.

Like I said above, I might PR this myself if I have time (I'm not *really* familiar with highlightjs so I'd have to spend time figuring it out), but no guarantees there. :)

**Comment by haltman-at** [comment]
Oops, I just realized... `for` is already a keyword, duh!  I'm going to mark that one as maybe unnecessary...

**Comment by abcoathup** [comment]
I am working on a PR (see https://github.com/highlightjs/highlight.js/issues/2047) to add solidity as a language into highlightjs as I want Solidity highlighting in a discourse forum (https://forum.zeppelin.solutions/)

I am just going through @haltman-at feedback.  I can also then do a PR for this repo too.

**Comment by abcoathup** [comment]
Have created PR https://github.com/highlightjs/highlightjs-solidity/pull/4 which updates most of @haltman-at feedback

**Comment by haltman-at** [comment]
Oh huh, reading up on highlight.js, I see there's different modes.  So actually the assembly stuff could be incorporated after all, just in assembly mode.  Neat.  Obviously not the most pressing issue though.

**Comment by marcoscaceres** [comment]
Yep, here as example of how we use it in a different project picking only the languages we need: https://github.com/w3c/respec-hljs

**Comment by haltman-at** [comment]
Another thing I just noticed: Numbers.  This highlighter includes `0b...` and `0o...` syntax for binary and octal; I can't find anything to indicate Solidity has ever used these.  Solidity *does*, however, allow underscores in the middle of numeric literals, which I don't think this highlighter accounts for.

**Comment by haltman-at** [comment]
One more thing I just noticed missing which I ended up fixing in my PR #5: The builtings `log0` through `log4`.  It's easy to forget about those, and, well, I certainly did!  But now they're in my PR.

**Comment by haltman-at** [comment]
Closing this since my PR made it in. :)
